#!/usr/bin/env ruby

puts "Depreciated: Run the following to install the new CLI tools:"
puts 
puts "vagrant plugin install vagrant-protobox"
puts 
puts "Once finished use the new command:"
puts
puts "vagrant protobox"
puts
exit
