#!/usr/bin/env ruby

require 'optparse'
require 'yaml'
require 'net/http'
require 'uri'
require 'open3'

options = {}

optparse = OptionParser.new do |opts|
  opts.banner = "Usage: protobox [command] [options]"

  opts.separator  ""
  opts.separator  "Commands"
  opts.separator  "     install [url]: install a new configuration from url"
  opts.separator  "     switch [name]: switch the configuration to [name] during vagrant up"
  opts.separator  "     provision: re-run the playbook to provision the box again"
  opts.separator  "     which [name]: check verisons and services are running"
  opts.separator  ""
  opts.separator  "Options"


  opts.on("-v", "--verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end

  opts.on_tail("-h", "--help", "Help") do
    puts optparse
  exit
  end
end

optparse.parse!

# Check required conditions
if ARGV.empty?
  puts optparse
  exit(-1)
end

# Setup vars
action = ARGV[0]
dir = Dir.pwd
protobox_dir = dir + '/.protobox'
boot_file = protobox_dir + '/config'
config_path = 'data/config'
config_dir = dir + '/' + config_path

# Create protobox dir if it doesn't exist
if !File.directory?(protobox_dir)
  Dir.mkdir(protobox_dir)
end

# Check if protobox boot file exists, if it doesn't create it here
if !File.file?(boot_file)
  File.open(boot_file, 'w') do |file|
    file.write(config_path + '/common.yml')
  end
end

# Check for boot file
if !File.file?(boot_file)
  puts "Boot file is missing: #{boot_file}\n"
  exit
end

# Process actions
case action
  # 
  # Switch: Switch between configurations
  # 
  when "switch" 
    config_name = ARGV[1]

    if config_name.nil?
        puts "Missing config name: protobox switch [name]"
        exit
    end

    location = config_dir + '/' + config_name + '.yml'

    # Check for file on the system
    if !File.file?(location)
        puts "Configuration file is missing: #{location}"
        exit
    end

    # Write the boot file
    File.open(boot_file, 'w') do |file|
        file.write(config_path + '/' + config_name + '.yml')
    end

    puts "You can now 'vagrant up' using the '#{config_name}' configuration"

  # 
  # Install: Install configuration from url
  # 
  when "install"
    url_name = ARGV[1]

    if url_name.nil?
      puts "Missing url: protobox install [url]"
      exit(-1)
    end

    # Build http
    uri = URI.parse(url_name.to_s)
    http = Net::HTTP.new(uri.host, uri.port)

    # Build request
    request = Net::HTTP::Get.new(uri.request_uri)
    request["User-Agent"] = "Protobox"

    # Get response
    response = http.request(request)

    # Check for invalid resonse code
    if response.code != "200"
      puts "Could not fetch url: #{url_name}"
      exit(-1)
    end

    # Store response
    body = response.body.to_s

    # Convert tabs to spaces
    body = body.gsub!(/(?:^ {2})|\G {2}/m, "  ")

    # Check for yaml document starter
    #if !!yaml[/^---/m]
    #  body = "---\n" + body
    #end

    # Validate response
    begin
      yaml_data = YAML.load(body)
    rescue Exception
      puts "Failed parse yaml for #{url_name}: #{$!}"
      #puts "Failed parse yaml for #{url_name}"
      exit(-1)
    end
    
    # Validate yaml
    if !yaml_data.instance_of?(Hash)
      puts "Invalid yaml for #{url_name}"
    end

    # Check for protobox data
    if yaml_data['protobox'].nil? or yaml_data['protobox']['version'].nil? or yaml_data['protobox']['document'].nil?
      puts "Document is missing protobox information"
      exit(-1)
    end

    document = yaml_data['protobox']['document']

    # Check for bad document name
    if document == 'common'
      puts "Invalid protobox document name"
      exit(-1)
    end

    # Save document to file system
    File.open(config_dir + '/' + document + '.yml', 'w') do |file|
      file.write(body)
    end

    # Write the boot file
    File.open(boot_file, 'w') do |file|
      file.write(config_path + '/' + document + '.yml')
    end

    puts "You can now 'vagrant up' using the '#{document}' configuration"

  # 
  # Provision: Run provisioner
  # 
  when "provision"

    # Open config file location
    vagrant_file = ''
    File.open(boot_file, 'r') do |f1|  
      while line = f1.gets  
        vagrant_file += line  
      end  
    end 

    # Check for missing data file
    if !File.file?(vagrant_file)
      puts "Data file is missing: #{vagrant_file}\n"
      exit
    end

    # Load settings into memory
    settings = YAML.load_file(vagrant_file)

    # Vagrant settings variable
    vagrant_vm = 'vagrant'

    params = Array.new

    # Ansible Provisioning
    if settings[vagrant_vm]['vm']['provision'].has_key?("ansible")
      ansible = settings[vagrant_vm]['vm']['provision']['ansible']
      playbook = "/vagrant/" + ansible['playbook']

      params << playbook

      if !ansible['inventory'].nil?
        params << "-i \\\"" + ansible['inventory'] + "\\\""
      end

      if !ansible['verbose'].nil?
        if ansible['verbose'] == 'vv' or ansible['verbose'] == 'vvv' or ansible['verbose'] == 'vvvv'
          params << "-" + ansible['verbose']
        else
          params << "--verbose"
        end
      end

      params << "--connection=local"

      if !ansible['extra_vars'].nil?
        extra_vars = ansible['extra_vars']
      else
        extra_vars = Hash.new
      end

      extra_vars['protobox_env'] = "vagrant"
      extra_vars['protobox_config'] = "/vagrant/" + vagrant_file

      params << "--extra-vars=\\\"" + extra_vars.map{|k,v| "#{k}=#{v}"}.join(" ").gsub("\"","\\\\\"") + "\\\"" unless extra_vars.empty?
    end 

    command = "vagrant ssh -c \"sudo ansible-playbook " + params.join(" ") + "\""

    #provision = %x{ #{command} }

    Open3.popen3(command) do |stdin, stdout, stderr, wait_thr|
      while line = stdout.gets
        puts line
      end

      #exit_status = wait_thr.value
      #unless exit_status.success?
      #  abort "FAILED !!! #{cmd}"
      #end
    end

  #
  # Which: Which version of things are running
  #
  when "which"
    service = ARGV[1]

    if service.nil?
      puts "Missing service: protobox which [service]"
      exit(-1)
    end

    case service
      # Protobox service
      when "version"

        # Open config file location
        vagrant_file = ''
        File.open(boot_file, 'r') do |f1|  
          while line = f1.gets  
            vagrant_file += line  
          end  
        end 

        # Check for missing data file
        if !File.file?(vagrant_file)
          puts "Data file is missing: #{vagrant_file}\n"
          exit
        end

        # Load settings into memory
        settings = YAML.load_file(vagrant_file)

        puts "Protobox version: " + settings['protobox']['version']

      # Config running
      when "config"

        # Open config file location
        vagrant_file = ''
        File.open(boot_file, 'r') do |f1|  
          while line = f1.gets  
            vagrant_file += line  
          end  
        end 

        # Check for missing data file
        if !File.file?(vagrant_file)
          puts "Data file is missing: #{vagrant_file}\n"
          exit
        end

        puts "Config file: " + vagrant_file

      else
        puts "Service not found [" + service + "]"
    end

  # 
  # Invalid option
  # 
  else 
    puts optparse
end
