#!/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby

puts "Please use our new installer by running the following commands: "
puts
puts "gem install protobox"
puts "protobox init"
puts
puts "If you have any issues, please file them at: "
puts "https://github.com/protobox/protobox/issues"
puts
exit
